export default {
  LOGO: 'LOGO',
  SEARCH: 'SEARCH',
  SMILE: 'SMILE',
  TIME: 'TIME',
  STORE: 'STORE',
  STORE_BLACK: 'STORE_BLACK',
  CLOSE: 'CLOSE',
  PLUS: 'PLUS',
  MINUS: 'MINUS',
  PREVIOUS: 'PREVIOUS',
  LEFT_ARROW: 'LEFT_ARROW',
  RIGHT_ARROW_BLACK: 'RIGHT_ARROW_BLACK'
}
