export const lang = {
    ko: {
      search: '이모티콘 검색',
      noShow: '검색 결과 없음',
      noRecent: '최근 전송 기록 없음',
      store: '이모티콘 스토어',
      pack: '이모티콘 팩',
    },
    en: {
      search: 'Search stickers',
      noShow: 'no Stickers to Show',
      noRecent: 'no Stickers Sent Recently',
      store: 'Sticker Store',
      pack: 'Sticker Pack',
    },
    ru: {
      search: 'Поиск стикеров',
      noShow: 'Нет стикеров для показа',
      noRecent: 'Нет стикеров для показа',
      store: 'Магазин стикеров',
      pack: 'Cтикеров пакет',
    },
    kk: {
      search: 'Стикер іздеу',
      noShow: 'Көрсетілетін стикерлер жоқ',
      noRecent: 'Көрсетілетін стикерлер жоқ',
      store: 'Стикер дүкені',
      pack: 'Стикерлер жинағы',
    },
    hi: {
      search: 'स्टिकर सर्च करें',
      noShow: 'दिखाने के लिए कोई स्टिकर नहीं है',
      noRecent: 'दिखाने के लिए कोई स्टिकर नहीं है',
      store: 'स्टिकर स्टोर',
      pack: 'स्टिकर पैक',
    },
    bn: {
      search: 'স্টিকার অনুসন্ধান করুন',
      noShow: 'দেখানোর জন্য কোনো স্টিকার নেই',
      noRecent: 'দেখানোর জন্য কোনো স্টিকার নেই',
      store: 'স্টিকার স্টোর',
      pack: 'স্টিকার প্যাকেজ',
    },
    mr: {
      search: 'स्टिकर शोधा',
      noShow: 'दर्शविण्यासाठी कोणतीही स्टिकर नाहीत',
      noRecent: 'दर्शविण्यासाठी कोणतीही स्टिकर नाहीत',
      store: 'स्टिकर स्टोअर',
      pack: 'स्टिकर पॅकेज',
    },
    es: {
      search: 'Buscar stickers',
      noShow: 'No hay stickers para mostrar',
      noRecent: 'No hay stickers para mostrar',
      store: 'Tienda de stickers',
      pack: 'Paquete de stickers',
    },
    vi: {
      search: 'Tìm kiếm nhãn dán',
      noShow: 'Không có nhãn dán để hiển thị',
      noRecent: 'Không có nhãn dán để hiển thị',
      store: 'Cửa hàng nhãn dán',
      pack: 'Gói nhãn dán',
    },
    fr: {
      search: 'Rechercher des stickers',
      noShow: 'Aucun sticker à afficher',
      noRecent: 'Aucun sticker à afficher',
      store: 'Magasin de stickers',
      pack: 'Paquet de stickers',
    },
    zh: {
      search: '搜索贴图',
      noShow: '无贴图可显示',
      noRecent: '无贴图可显示',
      store: '贴图商店',
      pack: '贴图包',
    },
    ar: {
      search: 'بحث عن ملصقات',
      noShow: 'لا توجد ملصقات لعرضها',
      noRecent: 'لا توجد ملصقات لعرضها',
      store: 'متجر الملصقات',
      pack: 'رزمة الملصقات',
    },
  }